### ISSUE TITLE
ER mit https

### ISSUE THREAD

**Issue by codepiX-dev** [BugBuster1701/privat-proxy#4]
Hallo, 

ich arbeite mit meinem Contao hinter einem Proxy. Bislang hat das mit Deiner Erweiterung auch immer problemlos funktioniert. Allerdings ist das ER nun auf https umgestellt worden, seitdem komme ich nicht mehr in den Erweiterungskatalog. 

Gibt es hier bereits eine Lösung?

**Comment by BugBuster1701** [comment]
Funktioniert bei mir. Kommt der Proxy denn auch raus oder stört da eventuell eine Firewall?

**Comment by codepiX-dev** [comment]
Wenn, dann wäre die Firewall auch vorher schon da gewesen und hätte Probleme gemacht. Habe die Probleme aber erst seit der Umstellung auf https. Hier meine Fehlermeldungen, evtl. kannst Du da mehr erkennen: 

`Warning: SoapClient::SoapClient(): SSL: crypto enabling timeout in system/modules/repository/classes/RepositoryBackendModule.php on line 124
#0 [internal function]: __error(2, 'SoapClient::Soa...', '/home/www/htdoc...', 124, Array)
#1 system/modules/repository/classes/RepositoryBackendModule.php(124): SoapClient->SoapClient('http://contao.o...', Array)
#2 system/modules/core/classes/BackendModule.php(100): RepositoryBackendModule->compile()
#3 system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate()
#4 system/modules/repository/classes/RepositoryCatalog.php(43): RepositoryBackendModule->generate()
#5 system/modules/core/classes/Backend.php(272): RepositoryCatalog->generate()
#6 contao/main.php(142): Contao\Backend->getBackendModule('repository_cata...')
#7 contao/main.php(293): Main->run()
#8 {main}

Warning: SoapClient::SoapClient(http://contao.org/services/repository.wsdl): failed to open stream: Cannot connect to HTTPS server through proxy in system/modules/repository/classes/RepositoryBackendModule.php on line 124
#0 [internal function]: __error(2, 'SoapClient::Soa...', '/home/www/htdoc...', 124, Array)
#1 system/modules/repository/classes/RepositoryBackendModule.php(124): SoapClient->SoapClient('http://contao.o...', Array)
#2 system/modules/core/classes/BackendModule.php(100): RepositoryBackendModule->compile()
#3 system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate()
#4 system/modules/repository/classes/RepositoryCatalog.php(43): RepositoryBackendModule->generate()
#5 system/modules/core/classes/Backend.php(272): RepositoryCatalog->generate()
#6 contao/main.php(142): Contao\Backend->getBackendModule('repository_cata...')
#7 contao/main.php(293): Main->run()
#8 {main}

Warning: SoapClient::SoapClient(): I/O warning : failed to load external entity "http://contao.org/services/repository.wsdl" in system/modules/repository/classes/RepositoryBackendModule.php on line 124
#0 [internal function]: __error(2, 'SoapClient::Soa...', '/home/www/htdoc...', 124, Array)
#1 system/modules/repository/classes/RepositoryBackendModule.php(124): SoapClient->SoapClient('http://contao.o...', Array)
#2 system/modules/core/classes/BackendModule.php(100): RepositoryBackendModule->compile()
#3 system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate()
#4 system/modules/repository/classes/RepositoryCatalog.php(43): RepositoryBackendModule->generate()
#5 system/modules/core/classes/Backend.php(272): RepositoryCatalog->generate()
#6 contao/main.php(142): Contao\Backend->getBackendModule('repository_cata...')
#7 contao/main.php(293): Main->run()
#8 {main}`

**Comment by BugBuster1701** [comment]
Wieso vorher auch? Wenn die Firewall nur Port 80 durchlässt, du aber nun auf 443 rauswillst, dann geht das halt nicht.
Außerdem sieht es hier so aus, als wenn bei dir im Backend noch nicht der "https..." Eintrag existiert:
```SoapClient->SoapClient('http://contao.o...', Array)```

Hier also erstmal die Adresse anpassen, dann sehen wir weiter.

**Comment by BugBuster1701** [comment]
Nutzt du Ubuntu 12.04 zufällig?

**Comment by codepiX-dev** [comment]
Klingt einleuchtend. Bin allerdings nicht der Administrator und kann das mit der Firewall daher nicht beantworten. Es läuft allerdings openSUSE 12.2 auf der Kiste. 

Ich habe die Adresse angepasst, allerdings bleibt der Fehler der gleiche: 

```
Warning: SoapClient::SoapClient(https://contao.org/services/repository.wsdl): failed to open stream: Cannot connect to HTTPS server through proxy
```

**Comment by BugBuster1701** [comment]
Könnte derselbe Fehler sein:
http://willbradley.name/2012/10/03/workaround-for-php-error-in-ubuntu-12-04-soapclient-ssl-crypto-enabling-timeout/

Ich werde mal heute Abend schauen ob ich das angepasst bekomme, sofern das in der Proxy Klasse geht, denn ich mache ja nicht die Soap Anforderung.

**Comment by codepiX-dev** [comment]
Okay, danke für Dein Feedback. Es liest sich ähnlich, stimmt.

**Comment by BugBuster1701** [comment]
Also ich kann da nicht helfen.
Testweise habe ich mal die TLS Crypto Möglichkeit rausgenommen, dann bekomme ich einen Fehler das keine passende Crypto Methode gefunden wurde.
Die Anpassungen aus dem Workaround habe ich mal in Contao eingebaut, da bekomme ich dann einen SSL Fehler (Handshake Prblem).
Wenn es wirklich ein openssl Bug ist in der alten libssl / openssl, dann hilft wohl nur ein Update.

**Comment by codepiX-dev** [comment]
Danke für Dein Feedback. Dann muss sich unser Administrator mal um ein Update bemühen.
